### ISSUE TITLE
MessageDraftOfDocumentPackageDeletedFromDiadocEventContent (UniversalCorrectionDocumentId)

### ISSUE THREAD

**Issue by mataranga** [skbkontur/edi-api-docs#6]
В описании класса [MessageDraftOfDocumentPackageDeletedFromDiadocEventContent ](https://edi-api-documentation.readthedocs.io/en/latest/structures/events/MessageDraftOfDocumentPackageDeletedFromDiadocEventContent.html?highlight=UniversalCorrectionDocumentId) нет поля `UniversalCorrectionDocumentId` а ниже в описании реквизитов это поле есть.

**Comment by mataranga** [comment]
Так же: 
- [MessageDraftOfDocumentPackageSignedByMeEventContent](https://edi-api-documentation.readthedocs.io/en/latest/structures/events/MessageDraftOfDocumentPackageSignedByMeEventContent.html?highlight=UniversalCorrectionDocumentId) 
- [MessageDiadocRevocationAcceptedForBuyerEventContent](https://edi-api-documentation.readthedocs.io/en/latest/structures/events/MessageDiadocRevocationAcceptedForBuyerEventContent.html?highlight=UniversalCorrectionDocumentId)
- [MessageDraftOfDocumentPackageSignedBySenderEventContent](https://edi-api-documentation.readthedocs.io/en/latest/structures/events/MessageDraftOfDocumentPackageSignedBySenderEventContent.html?highlight=UniversalCorrectionDocumentId)
- [MessageReceivedDiadocRoamingErrorEventContent](https://edi-api-documentation.readthedocs.io/en/latest/structures/events/MessageReceivedDiadocRoamingErrorEventContent.html?highlight=UniversalCorrectionDocumentId)

Везде `UniversalCorrectionDocumentId` нет в описании класса.

**Comment by akozlov78** [comment]
Исправлено.
